services: 
  application: 
    environment: 
      FILES_REPO: /tmp/files
      ENABLE_THREAD: false
    image: "FileAPI:latest"
    links: 
      - postgres
    ports: 
      - "8080:8082"
  postgres: 
    environment: 
      PGDATA: /tmp
      POSTGRES_DB: demodb
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes: 
      - "e:/docker/volume/postgres:/var/lib/postgresql/data"
version: "3"
